# theme: 'minima'
remote_theme: 'mmistakes/minimal-mistakes'
minimal_mistakes_skin: 'contrast' # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

locale: 'en-US'
title: 'Blake Randall'
title_separator: '-'
subtitle: 'Portfolio'
name: 'Blake Randall'
description: 'Portfolio'
url: 'https://randall.family'
baseurl: ''
teaser: '/assets/images/teaser.png'
logo: '/assets/images/logo.png'
masthead_title: 'Blake Randall'
breadcrumbs: false # true, false (default)
words_per_minute: 200
search: true
search_full_content: true
search_provider: 'lunr'

author:
  name: 'Blake Randall'
  avatar: '/assets/images/avatar.png'
  bio: ''
  location: 'Canada'
  email: 'blake@randall.family'
  url: 'https://randall.family'
  links:
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://linkedin.com/in/BlakeRandall'

footer:
  links:
    - label: 'Sitemap'
      icon: 'fas fa-fw fa-link'
      url: '/sitemap/'

include:
  - .htaccess
  - _pages
exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: 'utf-8'
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: 'America/Toronto'

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-giphy
  - jekyll-pdf-embed
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-giphy
  - jekyll-pdf-embed
  - jemoji

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _pages
  - scope:
      path: ''
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
  # _portfolio
  - scope:
      path: ''
      type: portfolio
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
